apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fraudlens
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment-api.yaml
  - deployment-worker.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicies.yaml
configMapGenerator:
  - name: fraudlens-backend-config
    envs:
      - backend.env
labels:
  - pairs:
      app.kubernetes.io/name: fraudlens
      app.kubernetes.io/part-of: fraudlens
    includeSelectors: true
