"""Summary: The alerts & review-workflow API (plan §5.4, §10.4, §16 Phase 9; endpoints 9-12). Every
route is scoped to the verified JWT `agency_id` (via `get_tenant`, never a path/body tenant) and
operates only on the agency's own rows via `AlertRepository`, so a cross-tenant alert id resolves to
404 with no existence leak (plan §6.4). `GET /alerts[/{id}]` list/detail the agency's alerts (the
detail surfaces the latest SAR draft + the append-only action trail). `POST /alerts/{id}/actions`
and `POST /alerts/{id}/sar/review` are thin: they enforce RBAC, resolve the acting user, hand a
Pydantic command to `AlertWorkflowService` — the single implementation of the transition sequence,
shared with the portfolio-demo bootstrap (rule 5) — commit, and project the result. The service
owns the domain behavior: validated status transitions (illegal → 409), note masking, agency-scoped
assignee validation (cross-tenant → 403), the `training_labels` row a resolve/dismiss produces, and
the PHI-free `audit_logs` rows (plan §8.4 "every action audited").

Key classes:
- (none)

Key functions:
- list_alerts: GET /alerts — the agency's alerts (newest first), optional status filter.
- get_alert: GET /alerts/{alertId} — alert detail (latest SAR draft + action history).
- act_on_alert: POST /alerts/{alertId}/actions — validated triage; terminal actions write labels.
- review_sar: POST /alerts/{alertId}/sar/review — approve/reject/edit the latest SAR draft.

Notes:
- Audited actions require a verified acting user; a token without a subject fails closed
  (`acting_user_required`, 401) so an `alert_actions.actor_id` / `training_labels.created_by` is
  never fabricated.
- The SAR PDF is generated by a deferred background task on its own session AFTER the approve
  commits, so approval is durable regardless of whether the PDF write succeeds (bounded retry).
  Scheduling it stays here deliberately — it is an HTTP-lifecycle concern the bootstrap must not do.
- The service flushes but never commits, so these handlers keep owning the transaction boundary
  (commit after the response projection is built, exactly as before the extraction).
"""

from __future__ import annotations

import uuid
from typing import Annotated

from fastapi import APIRouter, BackgroundTasks, Depends, Path, Query, Request
from sqlalchemy.ext.asyncio import AsyncSession

from fraudlens_backend.api.deps import (
    DbSessionDep,
    Permission,
    SettingsDep,
    audit_writer,
    enforce_permission,
    get_tenant,
    require_actor,
    require_permission,
)
from fraudlens_backend.backends.storage import get_storage_backend
from fraudlens_backend.db.models import AlertAction, AlertActionType, AlertStatus
from fraudlens_backend.db.repositories import AlertRepository, SarDraftRepository
from fraudlens_backend.db.repositories.alerts import AlertSummaryRow
from fraudlens_backend.models.alerts import (
    AlertActionRequest,
    AlertActionView,
    AlertDetailResponse,
    AlertListResponse,
    AlertView,
    SarReviewDecision,
    SarReviewRequest,
)
from fraudlens_backend.models.common import TenantContext
from fraudlens_backend.models.errors import AppError
from fraudlens_backend.models.sar import SarDraftView
from fraudlens_backend.sar.pdf import generate_sar_pdf
from fraudlens_backend.services.alert_workflow import (
    AlertActionCommand,
    AlertWorkflowService,
    SarReviewCommand,
)
from fraudlens_backend.services.sar_regeneration import sar_draft_to_view

router = APIRouter(tags=["alerts"])

TenantDep = Annotated[TenantContext, Depends(get_tenant)]
SarReviewDep = Annotated[TenantContext, Depends(require_permission(Permission.REVIEW_SAR))]

_DEFAULT_PAGE_LIMIT = 50
_MAX_PAGE_LIMIT = 200


def _repo(tenant: TenantContext, session: AsyncSession) -> AlertRepository:
    """Build an agency-scoped alert repository for the verified tenant."""
    return AlertRepository(session, uuid.UUID(tenant.agency_id))


def _sar_repo(tenant: TenantContext, session: AsyncSession) -> SarDraftRepository:
    """Build an agency-scoped SAR-draft repository for the verified tenant."""
    return SarDraftRepository(session, uuid.UUID(tenant.agency_id))


def _workflow(
    tenant: TenantContext, session: AsyncSession, request: Request
) -> AlertWorkflowService:
    """Build the tenant-scoped workflow service with this request's correlated audit writer."""
    return AlertWorkflowService(
        session,
        agency_id=uuid.UUID(tenant.agency_id),
        audit=audit_writer(tenant, session, request),
    )


def _to_alert_view(row: AlertSummaryRow) -> AlertView:
    """Project a joined Alert summary row onto the API summary view (PHI-free)."""
    alert = row.alert
    return AlertView(
        alert_id=str(alert.id),
        transaction_id=str(alert.transaction_id),
        run_id=str(alert.run_id),
        origin=alert.origin,
        status=alert.status,
        severity=alert.severity,
        amount=row.amount,
        currency=row.currency,
        assigned_to=str(alert.assigned_to) if alert.assigned_to is not None else None,
        assigned_to_name=row.assigned_to_name,
        review_flags=[dict(flag) for flag in (alert.review_flags or [])],
        created_at=alert.created_at,
        updated_at=alert.updated_at,
    )


def _to_action_view(action: AlertAction) -> AlertActionView:
    """Project an append-only AlertAction row onto the API view (note already PHI-masked)."""
    return AlertActionView(
        action_id=str(action.id),
        action=action.action,
        actor_id=str(action.actor_id),
        note=action.note,
        from_status=action.from_status,
        to_status=action.to_status,
        created_at=action.created_at,
    )


_to_sar_view = sar_draft_to_view  # single ORM→view mapping shared with the regeneration service.


def _permission_for_action(action: AlertActionType) -> Permission:
    """Map each alert action to its API-boundary permission."""
    if action == AlertActionType.DISMISS:
        return Permission.DISMISS_ALERT
    if action == AlertActionType.RESOLVE:
        return Permission.FINALIZE_ALERT
    return Permission.TRIAGE_ALERT


@router.get("/alerts", response_model=AlertListResponse)
async def list_alerts(
    tenant: TenantDep,
    session: DbSessionDep,
    limit: Annotated[int, Query(ge=1, le=_MAX_PAGE_LIMIT)] = _DEFAULT_PAGE_LIMIT,
    offset: Annotated[int, Query(ge=0)] = 0,
    status: Annotated[AlertStatus | None, Query()] = None,
) -> AlertListResponse:
    """Return a page of the agency's alerts (newest first), optionally filtered by status."""
    rows = await _repo(tenant, session).list_alerts(limit=limit, offset=offset, status=status)
    return AlertListResponse(alerts=[_to_alert_view(row) for row in rows])


@router.get("/alerts/{alertId}", response_model=AlertDetailResponse)
async def get_alert(
    alert_id: Annotated[uuid.UUID, Path(alias="alertId")],
    tenant: TenantDep,
    session: DbSessionDep,
) -> AlertDetailResponse:
    """Return an alert's detail (latest SAR draft + action history); 404 if missing/cross-tenant."""
    repo = _repo(tenant, session)
    row = await repo.get_alert_summary(alert_id)
    if row is None:
        raise AppError("alert_not_found")
    draft = await _sar_repo(tenant, session).get_for_run(row.alert.run_id)
    actions = await repo.list_actions(alert_id)
    return AlertDetailResponse(
        alert=_to_alert_view(row),
        sar_draft=_to_sar_view(draft) if draft is not None else None,
        actions=[_to_action_view(action) for action in actions],
    )


@router.post("/alerts/{alertId}/actions", response_model=AlertView)
async def act_on_alert(
    alert_id: Annotated[uuid.UUID, Path(alias="alertId")],
    payload: AlertActionRequest,
    request: Request,
    tenant: TenantDep,
    session: DbSessionDep,
) -> AlertView:
    """Apply a validated triage action; illegal transition → 409, cross-tenant assignee → 403."""
    enforce_permission(tenant, _permission_for_action(payload.action))
    actor_id = require_actor(tenant)
    await _workflow(tenant, session, request).apply_action(
        AlertActionCommand(
            alert_id=alert_id,
            actor_id=actor_id,
            action=payload.action,
            assignee_id=payload.assignee_id,
            note=payload.note,
            label=payload.label,
        )
    )
    row = await _repo(tenant, session).get_alert_summary(alert_id)
    if row is None:
        raise AppError("alert_not_found")
    await session.commit()
    return _to_alert_view(row)


@router.post("/alerts/{alertId}/sar/review", response_model=SarDraftView)
async def review_sar(  # noqa: PLR0913 - FastAPI handler: path + body + request + 3 injected deps.
    alert_id: Annotated[uuid.UUID, Path(alias="alertId")],
    payload: SarReviewRequest,
    request: Request,
    tenant: SarReviewDep,
    session: DbSessionDep,
    settings: SettingsDep,
    background_tasks: BackgroundTasks,
) -> SarDraftView:
    """Approve/reject/edit the alert's latest SAR draft; approve schedules a deferred PDF."""
    actor_id = require_actor(tenant)
    result = await _workflow(tenant, session, request).review_sar(
        SarReviewCommand(
            alert_id=alert_id,
            actor_id=actor_id,
            decision=payload.decision,
            edited_content=payload.edited_content,
        )
    )
    await session.commit()
    if payload.decision == SarReviewDecision.APPROVE:
        background_tasks.add_task(
            generate_sar_pdf,
            sessionmaker=request.app.state.db_sessionmaker,
            storage=get_storage_backend(settings),
            agency_id=uuid.UUID(tenant.agency_id),
            draft_id=uuid.UUID(result.draft.sar_draft_id),
            max_attempts=settings.sar_pdf_max_attempts,
        )
    return result.draft
