"""Summary: The alerts & review-workflow API (plan §5.4, §10.4, §16 Phase 9; endpoints 9-12). Every
route is scoped to the verified JWT `agency_id` (via `get_tenant`, never a path/body tenant) and
operates only on the agency's own rows via `AlertRepository`, so a cross-tenant alert id resolves to
404 with no existence leak (plan §6.4). `GET /alerts[/{id}]` list/detail the agency's alerts (the
detail surfaces the latest SAR draft + the append-only action trail). `POST /alerts/{id}/actions`
applies a centralized, validated status transition (assign/comment/escalate/resolve/dismiss; an
illegal transition is 409), masks the free-text note, validates an assignee belongs to the agency
(cross-tenant assignee → 403), and — on `resolve` / `dismiss` — writes the `training_labels` row
the model lifecycle consumes. `POST /alerts/{id}/sar/review` approves/rejects/edits the latest SAR
draft (an edit is a new masked version; approve schedules a deferred PDF that never blocks
approval). Every action and review writes a PHI-free `audit_logs` row (plan §8.4 "every action
audited").

Key classes:
- (none)

Key functions:
- list_alerts: GET /alerts — the agency's alerts (newest first), optional status filter.
- get_alert: GET /alerts/{alertId} — alert detail (latest SAR draft + action history).
- act_on_alert: POST /alerts/{alertId}/actions — validated triage; terminal actions write labels.
- review_sar: POST /alerts/{alertId}/sar/review — approve/reject/edit the latest SAR draft.
- sar_decision_allowed: pure check of whether a review decision is legal from a draft's status.

Notes:
- Audited actions require a verified acting user; a token without a subject fails closed
  (`acting_user_required`, 401) so an `alert_actions.actor_id` / `training_labels.created_by` is
  never fabricated.
- The SAR PDF is generated by a deferred background task on its own session AFTER the approve
  commits, so approval is durable regardless of whether the PDF write succeeds (bounded retry).
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from typing import Annotated, cast

from fastapi import APIRouter, BackgroundTasks, Depends, Path, Query, Request
from sqlalchemy.ext.asyncio import AsyncSession

from fraudlens_backend.api.deps import (
    DbSessionDep,
    Permission,
    SettingsDep,
    audit_writer,
    enforce_permission,
    get_tenant,
    require_actor,
    require_permission,
)
from fraudlens_backend.backends.storage import get_storage_backend
from fraudlens_backend.db.models import AlertAction, AlertActionType, AlertStatus
from fraudlens_backend.db.models.enums import LabelSource, SarStatus, TrainingLabelType
from fraudlens_backend.db.repositories import (
    AlertRepository,
    AuditLogRepository,
    SarDraftRepository,
)
from fraudlens_backend.db.repositories.alerts import (
    AlertSummaryRow,
    load_label_maturity_days,
    next_alert_status,
)
from fraudlens_backend.models.alerts import (
    AlertActionRequest,
    AlertActionView,
    AlertDetailResponse,
    AlertListResponse,
    AlertView,
    SarReviewDecision,
    SarReviewRequest,
)
from fraudlens_backend.models.common import TenantContext
from fraudlens_backend.models.errors import AppError
from fraudlens_backend.models.sar import SarDraftView
from fraudlens_backend.sar.pdf import generate_sar_pdf
from fraudlens_backend.services.sar_regeneration import sar_draft_to_view
from fraudlens_core.phi import MaskingReport, mask_text

router = APIRouter(tags=["alerts"])

TenantDep = Annotated[TenantContext, Depends(get_tenant)]
SarReviewDep = Annotated[TenantContext, Depends(require_permission(Permission.REVIEW_SAR))]

_DEFAULT_PAGE_LIMIT = 50
_MAX_PAGE_LIMIT = 200

# SAR statuses from which no further review decision is legal (the draft is decided).
_SAR_TERMINAL: frozenset[SarStatus] = frozenset({SarStatus.APPROVED, SarStatus.REJECTED})


def _repo(tenant: TenantContext, session: AsyncSession) -> AlertRepository:
    """Build an agency-scoped alert repository for the verified tenant."""
    return AlertRepository(session, uuid.UUID(tenant.agency_id))


def _sar_repo(tenant: TenantContext, session: AsyncSession) -> SarDraftRepository:
    """Build an agency-scoped SAR-draft repository for the verified tenant."""
    return SarDraftRepository(session, uuid.UUID(tenant.agency_id))


def _to_alert_view(row: AlertSummaryRow) -> AlertView:
    """Project a joined Alert summary row onto the API summary view (PHI-free)."""
    alert = row.alert
    return AlertView(
        alert_id=str(alert.id),
        transaction_id=str(alert.transaction_id),
        run_id=str(alert.run_id),
        origin=alert.origin,
        status=alert.status,
        severity=alert.severity,
        amount=row.amount,
        currency=row.currency,
        assigned_to=str(alert.assigned_to) if alert.assigned_to is not None else None,
        review_flags=[dict(flag) for flag in (alert.review_flags or [])],
        created_at=alert.created_at,
        updated_at=alert.updated_at,
    )


def _to_action_view(action: AlertAction) -> AlertActionView:
    """Project an append-only AlertAction row onto the API view (note already PHI-masked)."""
    return AlertActionView(
        action_id=str(action.id),
        action=action.action,
        actor_id=str(action.actor_id),
        note=action.note,
        from_status=action.from_status,
        to_status=action.to_status,
        created_at=action.created_at,
    )


_to_sar_view = sar_draft_to_view  # single ORM→view mapping shared with the regeneration service.


def _permission_for_action(action: AlertActionType) -> Permission:
    """Map each alert action to its API-boundary permission."""
    if action == AlertActionType.DISMISS:
        return Permission.DISMISS_ALERT
    if action == AlertActionType.RESOLVE:
        return Permission.FINALIZE_ALERT
    return Permission.TRIAGE_ALERT


def sar_decision_allowed(status: SarStatus, decision: SarReviewDecision, *, has_edit: bool) -> bool:
    """Return whether a review decision is legal from the draft's current status (plan §10.4).

    A decided draft (approved/rejected) admits nothing further. A `failed` draft cannot be approved
    unless the reviewer supplies replacement content (an edit); reject/edit are legal otherwise.
    """
    if status in _SAR_TERMINAL:
        return False
    if decision == SarReviewDecision.APPROVE:
        return status != SarStatus.FAILED or has_edit
    return True


def _action_metadata(
    payload: AlertActionRequest, *, from_status: str, to_status: AlertStatus
) -> dict[str, str]:
    """Build the PHI-free audit metadata for a triage action (ids/enums only — never the note)."""
    metadata = {
        "action": payload.action.value,
        "fromStatus": from_status,
        "toStatus": to_status.value,
    }
    if payload.action == AlertActionType.ASSIGN and payload.assignee_id is not None:
        metadata["assigneeId"] = str(payload.assignee_id)
    if payload.action == AlertActionType.RESOLVE and payload.label is not None:
        metadata["label"] = payload.label.value
    return metadata


async def _record_text_phi_mask(  # noqa: PLR0913 - explicit audit fields keep call sites clear.
    writer: AuditLogRepository,
    *,
    actor_id: uuid.UUID,
    resource_type: str,
    resource_id: str,
    report: MaskingReport | None,
    source: str,
) -> None:
    """Record counts-only PHI masking for reviewer-entered free text."""
    if report is None or report.total == 0:
        return
    await writer.record(
        actor_id=actor_id,
        action="phi_mask",
        resource_type=resource_type,
        resource_id=resource_id,
        metadata={
            "source": source,
            "maskedCount": str(report.total),
            "categories": ",".join(f"{key}:{value}" for key, value in report.categories.items()),
        },
    )


@router.get("/alerts", response_model=AlertListResponse)
async def list_alerts(
    tenant: TenantDep,
    session: DbSessionDep,
    limit: Annotated[int, Query(ge=1, le=_MAX_PAGE_LIMIT)] = _DEFAULT_PAGE_LIMIT,
    offset: Annotated[int, Query(ge=0)] = 0,
    status: Annotated[AlertStatus | None, Query()] = None,
) -> AlertListResponse:
    """Return a page of the agency's alerts (newest first), optionally filtered by status."""
    rows = await _repo(tenant, session).list_alerts(limit=limit, offset=offset, status=status)
    return AlertListResponse(alerts=[_to_alert_view(row) for row in rows])


@router.get("/alerts/{alertId}", response_model=AlertDetailResponse)
async def get_alert(
    alert_id: Annotated[uuid.UUID, Path(alias="alertId")],
    tenant: TenantDep,
    session: DbSessionDep,
) -> AlertDetailResponse:
    """Return an alert's detail (latest SAR draft + action history); 404 if missing/cross-tenant."""
    repo = _repo(tenant, session)
    row = await repo.get_alert_summary(alert_id)
    if row is None:
        raise AppError("alert_not_found")
    draft = await _sar_repo(tenant, session).get_for_run(row.alert.run_id)
    actions = await repo.list_actions(alert_id)
    return AlertDetailResponse(
        alert=_to_alert_view(row),
        sar_draft=_to_sar_view(draft) if draft is not None else None,
        actions=[_to_action_view(action) for action in actions],
    )


@router.post("/alerts/{alertId}/actions", response_model=AlertView)
async def act_on_alert(
    alert_id: Annotated[uuid.UUID, Path(alias="alertId")],
    payload: AlertActionRequest,
    request: Request,
    tenant: TenantDep,
    session: DbSessionDep,
) -> AlertView:
    """Apply a validated triage action; illegal transition → 409, cross-tenant assignee → 403."""
    enforce_permission(tenant, _permission_for_action(payload.action))
    repo = _repo(tenant, session)
    actor_id = require_actor(tenant)
    alert = await repo.get(alert_id)
    if alert is None:
        raise AppError("alert_not_found")
    target = next_alert_status(alert.status, payload.action)
    if target is None:
        raise AppError("invalid_alert_transition")
    from_status = alert.status.value
    assigned_to: uuid.UUID | None = None
    if payload.action == AlertActionType.ASSIGN:
        # The request validator guarantees an assignee for assign; narrow the type for mypy.
        assignee_id = cast(uuid.UUID, payload.assignee_id)
        if not await repo.user_in_agency(assignee_id):
            raise AppError("assignee_not_in_agency")
        assigned_to = assignee_id
    if payload.action == AlertActionType.RESOLVE and payload.label is not None:
        maturity_days = await load_label_maturity_days(session)
        await repo.create_training_label(
            transaction_id=alert.transaction_id,
            run_id=alert.run_id,
            label=payload.label,
            created_by=actor_id,
            matured_at=datetime.now(UTC) + timedelta(days=maturity_days),
        )
    elif payload.action == AlertActionType.DISMISS:
        maturity_days = await load_label_maturity_days(session)
        await repo.create_training_label(
            transaction_id=alert.transaction_id,
            run_id=alert.run_id,
            label=TrainingLabelType.FALSE_POSITIVE,
            source=LabelSource.ANALYST_DISMISS,
            created_by=actor_id,
            matured_at=datetime.now(UTC) + timedelta(days=maturity_days),
        )
    masked_note_result = mask_text(payload.note) if payload.note else None
    masked_note = masked_note_result.value if masked_note_result is not None else None
    await repo.record_action(
        alert=alert,
        actor_id=actor_id,
        action=payload.action,
        to_status=target,
        note=masked_note,
        assigned_to=assigned_to,
    )
    writer = audit_writer(tenant, session, request)
    await _record_text_phi_mask(
        writer,
        actor_id=actor_id,
        resource_type="alert",
        resource_id=str(alert_id),
        report=masked_note_result.report if masked_note_result is not None else None,
        source="alert.action_note",
    )
    await writer.record(
        actor_id=actor_id,
        action=f"alert.{payload.action.value}",
        resource_type="alert",
        resource_id=str(alert_id),
        metadata=_action_metadata(payload, from_status=from_status, to_status=target),
    )
    # Refresh so the server-side `updated_at` (onupdate) is loaded before projection (else a
    # post-commit attribute access would lazy-load in a sync context); mirrors the rules handler.
    await session.refresh(alert)
    row = await repo.get_alert_summary(alert_id)
    if row is None:
        raise AppError("alert_not_found")
    await session.commit()
    return _to_alert_view(row)


@router.post("/alerts/{alertId}/sar/review", response_model=SarDraftView)
async def review_sar(  # noqa: PLR0913 - FastAPI handler: path + body + request + 3 injected deps.
    alert_id: Annotated[uuid.UUID, Path(alias="alertId")],
    payload: SarReviewRequest,
    request: Request,
    tenant: SarReviewDep,
    session: DbSessionDep,
    settings: SettingsDep,
    background_tasks: BackgroundTasks,
) -> SarDraftView:
    """Approve/reject/edit the alert's latest SAR draft; approve schedules a deferred PDF."""
    repo = _repo(tenant, session)
    actor_id = require_actor(tenant)
    alert = await repo.get(alert_id)
    if alert is None:
        raise AppError("alert_not_found")
    sar_repo = _sar_repo(tenant, session)
    draft = await sar_repo.get_for_run(alert.run_id)
    if draft is None:
        raise AppError("sar_draft_not_found")
    has_edit = bool(payload.edited_content and payload.edited_content.strip())
    if not sar_decision_allowed(draft.status, payload.decision, has_edit=has_edit):
        raise AppError("invalid_sar_transition")
    target = draft
    edited_report: MaskingReport | None = None
    if has_edit and payload.edited_content is not None:
        masked_edit = mask_text(payload.edited_content)
        edited_report = masked_edit.report
        target = await sar_repo.create_edited_version(
            base=draft,
            content=masked_edit.value,
            created_by=actor_id,
            alert_id=alert.id,
        )
    if payload.decision == SarReviewDecision.APPROVE:
        await sar_repo.set_review_status(target, status=SarStatus.APPROVED, reviewed_by=actor_id)
    elif payload.decision == SarReviewDecision.REJECT:
        await sar_repo.set_review_status(target, status=SarStatus.REJECTED, reviewed_by=actor_id)
    writer = audit_writer(tenant, session, request)
    await _record_text_phi_mask(
        writer,
        actor_id=actor_id,
        resource_type="sar_draft",
        resource_id=str(target.id),
        report=edited_report,
        source="sar.review_edit",
    )
    await writer.record(
        actor_id=actor_id,
        action=f"sar.{payload.decision.value}",
        resource_type="sar_draft",
        resource_id=str(target.id),
        metadata={"decision": payload.decision.value, "status": target.status.value},
    )
    draft_id = target.id
    await session.commit()
    if payload.decision == SarReviewDecision.APPROVE:
        background_tasks.add_task(
            generate_sar_pdf,
            sessionmaker=request.app.state.db_sessionmaker,
            storage=get_storage_backend(settings),
            agency_id=uuid.UUID(tenant.agency_id),
            draft_id=draft_id,
            max_attempts=settings.sar_pdf_max_attempts,
        )
    return _to_sar_view(target)
