"""initial schema — all §9 tables (core + MLOps + event log)

Creates every FraudLens table with its indexes, foreign keys, and constraints (plan §9).
Tenant-scoped tables carry an indexed NOT NULL ``agency_id`` (nullable on the four
global-or-tenant tables); the seven platform tables carry none. Types are portable so the
same migration runs on Postgres (prod/local-demo) and SQLite (the DB test suite): UUID PKs,
``_json()`` (JSONB on Postgres, JSON elsewhere), and string-stored enums whose values are
the member ``.value`` (native_enum=False). ``render_as_batch`` keeps future ALTERs SQLite-safe.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-12
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _json() -> sa.types.TypeEngine[object]:
    """Portable JSON column type: JSONB on Postgres, generic JSON on other dialects."""
    return sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agencies")),
        sa.UniqueConstraint("slug", name=op.f("uq_agencies_slug")),
    )
    op.create_table(
        "training_datasets",
        sa.Column("snapshot_query", _json(), nullable=False),
        sa.Column("label_window", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("feature_spec", _json(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_datasets")),
    )
    op.create_table(
        "aml_rules",
        sa.Column("agency_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum(
                "structuring",
                "velocity",
                "high_risk_geography",
                "round_amount",
                "threshold_evasion",
                "rapid_movement",
                name="amlruletype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("params", _json(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity", native_enum=False),
            nullable=False,
        ),
        sa.Column("weight", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_aml_rules_agency_id_agencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aml_rules")),
    )
    with op.batch_alter_table("aml_rules", schema=None) as batch_op:
        batch_op.create_index("ix_aml_rules_agency_id_code", ["agency_id", "code"], unique=False)

    op.create_table(
        "job_executions",
        sa.Column("agency_id", sa.Uuid(), nullable=True),
        sa.Column(
            "job_type",
            sa.Enum(
                "seed",
                "csv_import",
                "train",
                "retrain",
                "ingest_rag",
                "drift_scan",
                "batch_score",
                name="jobtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "succeeded", "failed", name="jobstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("payload", _json(), nullable=False),
        sa.Column("result", _json(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_job_executions_agency_id_agencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_executions")),
    )
    with op.batch_alter_table("job_executions", schema=None) as batch_op:
        batch_op.create_index("ix_job_executions_agency_id", ["agency_id"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("origin_account", sa.String(length=64), nullable=False),
        sa.Column("dest_account", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=64), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("features", _json(), nullable=False),
        sa.Column("feature_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "risk_band",
            sa.Enum("low", "medium", "high", "critical", name="riskband", native_enum=False),
            nullable=True,
        ),
        sa.Column("latest_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_transactions_agency_id_agencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint(
            "agency_id", "external_id", name="uq_transactions_agency_id_external_id"
        ),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_transactions_agency_id_occurred_at", ["agency_id", "occurred_at"], unique=False
        )
        batch_op.create_index(
            "ix_transactions_agency_id_risk_band", ["agency_id", "risk_band"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("analyst", "reviewer", "admin", name="userrole", native_enum=False),
            nullable=False,
        ),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_users_agency_id_agencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_agency_id_email", ["agency_id", "email"], unique=False)

    op.create_table(
        "analysis_runs",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "completed", "failed", name="runstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column(
            "risk_band",
            sa.Enum("low", "medium", "high", "critical", name="riskband", native_enum=False),
            nullable=True,
        ),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("rules_version", sa.String(length=128), nullable=True),
        sa.Column("rag_version", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=128), nullable=True),
        sa.Column("triggered_by", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_analysis_runs_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_analysis_runs_transaction_id_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"], ["users.id"], name=op.f("fk_analysis_runs_triggered_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
    )
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_analysis_runs_agency_id_created_at", ["agency_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_analysis_runs_agency_id_status", ["agency_id", "status"], unique=False
        )

    op.create_table(
        "audit_logs",
        sa.Column("agency_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=128), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("metadata", _json(), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_audit_logs_agency_id_agencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_logs_agency_id_created_at", ["agency_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_audit_logs_resource_type_resource_id",
            ["resource_type", "resource_id"],
            unique=False,
        )

    op.create_table(
        "model_training_runs",
        sa.Column(
            "trigger",
            sa.Enum("manual", "scheduled", name="modeltrigger", native_enum=False),
            nullable=False,
        ),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "succeeded", "failed", name="jobstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("params", _json(), nullable=False),
        sa.Column("metrics", _json(), nullable=False),
        sa.Column("artifact_uri", sa.String(length=512), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_model_training_runs_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["training_datasets.id"],
            name=op.f("fk_model_training_runs_dataset_id_training_datasets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_training_runs")),
    )
    op.create_table(
        "system_config",
        sa.Column("agency_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", _json(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_system_config_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_system_config_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_config")),
        sa.UniqueConstraint("agency_id", "key", name="uq_system_config_agency_id"),
    )
    op.create_table(
        "alerts",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open", "in_review", "resolved", "dismissed", name="alertstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity", native_enum=False),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("review_flags", _json(), nullable=False),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_alerts_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name=op.f("fk_alerts_assigned_to_users")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_alerts_run_id_analysis_runs")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_alerts_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alerts_agency_id_assigned_to", ["agency_id", "assigned_to"], unique=False
        )
        batch_op.create_index("ix_alerts_agency_id_status", ["agency_id", "status"], unique=False)

    op.create_table(
        "analysis_results",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("fraud_probability", sa.Float(), nullable=False),
        sa.Column("shap_values", _json(), nullable=False),
        sa.Column("top_features", _json(), nullable=False),
        sa.Column("rule_hits", _json(), nullable=False),
        sa.Column("combined_score", sa.Float(), nullable=False),
        sa.Column(
            "risk_band",
            sa.Enum("low", "medium", "high", "critical", name="riskband", native_enum=False),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_analysis_results_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_analysis_results_run_id_analysis_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_results")),
        sa.UniqueConstraint("run_id", name="uq_analysis_results_run_id"),
    )
    with op.batch_alter_table("analysis_results", schema=None) as batch_op:
        batch_op.create_index("ix_analysis_results_agency_id", ["agency_id"], unique=False)

    op.create_table(
        "analysis_run_events",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "run.started",
                "step.rules.completed",
                "step.scoring.completed",
                "step.shap.completed",
                "step.rag.completed",
                "sar.started",
                "run.completed",
                "run.failed",
                name="analysisruneventtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payload", _json(), nullable=False),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_analysis_run_events_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_analysis_run_events_run_id_analysis_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_run_events")),
        sa.UniqueConstraint("run_id", "seq", name="uq_analysis_run_events_run_id"),
    )
    with op.batch_alter_table("analysis_run_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_analysis_run_events_agency_id_run_id_seq",
            ["agency_id", "run_id", "seq"],
            unique=False,
        )

    op.create_table(
        "model_versions",
        sa.Column("version_label", sa.String(length=64), nullable=False),
        sa.Column("training_run_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_uri", sa.String(length=512), nullable=False),
        sa.Column("feature_spec", _json(), nullable=False),
        sa.Column("metrics", _json(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "candidate",
                "shadow",
                "canary",
                "active",
                "archived",
                "rejected",
                name="modelversionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_model_versions_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["training_run_id"],
            ["model_training_runs.id"],
            name=op.f("fk_model_versions_training_run_id_model_training_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("version_label", name=op.f("uq_model_versions_version_label")),
    )
    op.create_table(
        "rag_retrievals",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("chunks", _json(), nullable=False),
        sa.Column("rag_version", sa.String(length=128), nullable=False),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_rag_retrievals_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_rag_retrievals_run_id_analysis_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_retrievals")),
        sa.UniqueConstraint("run_id", name="uq_rag_retrievals_run_id"),
    )
    with op.batch_alter_table("rag_retrievals", schema=None) as batch_op:
        batch_op.create_index("ix_rag_retrievals_agency_id", ["agency_id"], unique=False)

    op.create_table(
        "training_labels",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "label",
            sa.Enum(
                "confirmed_fraud",
                "false_positive",
                "false_negative",
                "benign",
                name="traininglabeltype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("analyst_review", name="labelsource", native_enum=False),
            nullable=False,
        ),
        sa.Column("matured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_training_labels_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_training_labels_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_training_labels_run_id_analysis_runs")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_training_labels_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_labels")),
    )
    with op.batch_alter_table("training_labels", schema=None) as batch_op:
        batch_op.create_index("ix_training_labels_agency_id", ["agency_id"], unique=False)

    op.create_table(
        "alert_actions",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "assign",
                "comment",
                "escalate",
                "resolve",
                "dismiss",
                name="alertactiontype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=True),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_alert_actions_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_alert_actions_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["alerts.id"], name=op.f("fk_alert_actions_alert_id_alerts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_actions")),
    )
    with op.batch_alter_table("alert_actions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alert_actions_agency_id_alert_id", ["agency_id", "alert_id"], unique=False
        )

    op.create_table(
        "drift_reports",
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("window", sa.String(length=64), nullable=False),
        sa.Column("metrics", _json(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity", native_enum=False),
            nullable=False,
        ),
        sa.Column("advisory", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_drift_reports_model_version_id_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drift_reports")),
    )
    op.create_table(
        "model_deployments",
        sa.Column("active_version_id", sa.Uuid(), nullable=False),
        sa.Column("canary_version_id", sa.Uuid(), nullable=True),
        sa.Column("canary_percent", sa.Integer(), nullable=False),
        sa.Column("previous_active_version_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_version_id"],
            ["model_versions.id"],
            name=op.f("fk_model_deployments_active_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["canary_version_id"],
            ["model_versions.id"],
            name=op.f("fk_model_deployments_canary_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_active_version_id"],
            ["model_versions.id"],
            name=op.f("fk_model_deployments_previous_active_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_model_deployments_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_deployments")),
    )
    op.create_table(
        "model_evaluations",
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_version_id", sa.Uuid(), nullable=True),
        sa.Column("metrics", _json(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["baseline_version_id"],
            ["model_versions.id"],
            name=op.f("fk_model_evaluations_baseline_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_model_evaluations_model_version_id_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_evaluations")),
    )
    op.create_table(
        "model_inference_logs",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("was_canary", sa.Boolean(), nullable=False),
        sa.Column("fraud_probability", sa.Float(), nullable=False),
        sa.Column("feature_hash", sa.String(length=64), nullable=False),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_model_inference_logs_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_model_inference_logs_model_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_model_inference_logs_run_id_analysis_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_inference_logs")),
    )
    with op.batch_alter_table("model_inference_logs", schema=None) as batch_op:
        batch_op.create_index("ix_model_inference_logs_agency_id", ["agency_id"], unique=False)

    op.create_table(
        "sar_drafts",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=128), nullable=False),
        sa.Column("prompt_hash", sa.String(length=128), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("structured", _json(), nullable=False),
        sa.Column("citations", _json(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "reviewed",
                "approved",
                "rejected",
                "failed",
                name="sarstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("token_usage", _json(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("pdf_blob_url", sa.String(length=512), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("fk_sar_drafts_agency_id_agencies")
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["alerts.id"], name=op.f("fk_sar_drafts_alert_id_alerts")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_sar_drafts_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_sar_drafts_reviewed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_sar_drafts_run_id_analysis_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sar_drafts")),
    )
    with op.batch_alter_table("sar_drafts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sar_drafts_agency_id_run_id", ["agency_id", "run_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sar_drafts", schema=None) as batch_op:
        batch_op.drop_index("ix_sar_drafts_agency_id_run_id")

    op.drop_table("sar_drafts")
    with op.batch_alter_table("model_inference_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_model_inference_logs_agency_id")

    op.drop_table("model_inference_logs")
    op.drop_table("model_evaluations")
    op.drop_table("model_deployments")
    op.drop_table("drift_reports")
    with op.batch_alter_table("alert_actions", schema=None) as batch_op:
        batch_op.drop_index("ix_alert_actions_agency_id_alert_id")

    op.drop_table("alert_actions")
    with op.batch_alter_table("training_labels", schema=None) as batch_op:
        batch_op.drop_index("ix_training_labels_agency_id")

    op.drop_table("training_labels")
    with op.batch_alter_table("rag_retrievals", schema=None) as batch_op:
        batch_op.drop_index("ix_rag_retrievals_agency_id")

    op.drop_table("rag_retrievals")
    op.drop_table("model_versions")
    with op.batch_alter_table("analysis_run_events", schema=None) as batch_op:
        batch_op.drop_index("ix_analysis_run_events_agency_id_run_id_seq")

    op.drop_table("analysis_run_events")
    with op.batch_alter_table("analysis_results", schema=None) as batch_op:
        batch_op.drop_index("ix_analysis_results_agency_id")

    op.drop_table("analysis_results")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_alerts_agency_id_status")
        batch_op.drop_index("ix_alerts_agency_id_assigned_to")

    op.drop_table("alerts")
    op.drop_table("system_config")
    op.drop_table("model_training_runs")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_resource_type_resource_id")
        batch_op.drop_index("ix_audit_logs_agency_id_created_at")

    op.drop_table("audit_logs")
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_analysis_runs_agency_id_status")
        batch_op.drop_index("ix_analysis_runs_agency_id_created_at")

    op.drop_table("analysis_runs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_agency_id_email")

    op.drop_table("users")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_agency_id_risk_band")
        batch_op.drop_index("ix_transactions_agency_id_occurred_at")

    op.drop_table("transactions")
    with op.batch_alter_table("job_executions", schema=None) as batch_op:
        batch_op.drop_index("ix_job_executions_agency_id")

    op.drop_table("job_executions")
    with op.batch_alter_table("aml_rules", schema=None) as batch_op:
        batch_op.drop_index("ix_aml_rules_agency_id_code")

    op.drop_table("aml_rules")
    op.drop_table("training_datasets")
    op.drop_table("agencies")
    # ### end Alembic commands ###
