"""Summary: Offline citation-quality gate over REAL model output plus the current drafting path.

Key classes:
- (none)

Key functions:
- (none)

Notes:
- The precision/recall half of this suite now runs over `tests/fixtures/sar_replay_corpus.json`:
  40 real per-case outputs from the persisted vLLM run, both arms, including the cases that
  fabricated citation ids. The previous version drafted through `MockSarDrafter`, whose
  `cited_regulations` IS the offered set, so precision and recall were 1.0 by construction and no
  assertion could ever have failed. `test_the_corpus_breaches_precision_when_the_gate_is_bypassed`
  is the standing proof that this is no longer true: the same corpus, ungated, misses the
  committed precision floor.
- Required-fact coverage stays on the CURRENT production path (prompt v2 + the deterministic
  gate). Coverage is an exact-substring metric against ground-truth facts, and the replay corpus
  was generated by prompt v1, which never asked a model to restate them in canonical form —
  measuring coverage there would grade the retired prompt, not the shipped one.
- The keyless mock and production parse/gate path run without providers, sockets, or credentials.
"""

from __future__ import annotations

import statistics
from datetime import UTC
from pathlib import Path

import pytest
from quality_gates import production_gate, replay_gate
from sar_replay import (
    AWQ_ARM,
    BF16_ARM,
    REPLAY_PILOT_PATH,
    ReplayArmOutput,
    ReplayCase,
    load_replay_corpus,
)

from fraudlens_backend.sar.drafter_mock import MockSarDrafter
from fraudlens_backend.sar.egress import load_egress_policy, project_for_model
from fraudlens_backend.sar.evidence import SarEvidenceCatalog
from fraudlens_backend.sar.prompt import SarPromptTemplate
from fraudlens_backend.sar.schema import SarSchemaError, parse_only
from fraudlens_core import RiskBand, TransactionDirection
from fraudlens_ml.evaluation import citation_precision_recall, required_fact_coverage
from fraudlens_ml.rag.citations import escape_as_data
from fraudlens_ml.rag.ingest import chunk_corpus, load_corpus
from fraudlens_ml.sar import SarCitation, SarDraftContent, SarInput
from lib.quality.config import load_quality_config
from lib.sar_eval.config import DEFAULT_SAR_EVAL_CONFIG, load_sar_eval_config
from lib.sar_eval.scenarios import generate_scenarios
from lib.vllm_bench.cascade_pilot import CascadeReplayPilot

pytestmark = pytest.mark.quality
_REPO_ROOT = Path(__file__).resolve().parents[2]
_EXPECTED_SCENARIOS = 32
# The replay corpus carries no projection, and the replay policy disables every catalog rule:
# prompt v1 never asked for asserted facts, so there is nothing for a catalog to be matched to.
_EMPTY_CATALOG = SarEvidenceCatalog(facts=())


def _citation_map() -> dict[str, SarCitation]:
    """Build one exact digest-verifiable citation per corpus provision."""
    result: dict[str, SarCitation] = {}
    for chunk in chunk_corpus(load_corpus(_REPO_ROOT / "data" / "regulations")):
        result.setdefault(
            chunk.citation,
            SarCitation(
                citation=chunk.citation,
                title=chunk.title,
                source=chunk.source,
                snippet=escape_as_data(chunk.text),
            ),
        )
    return result


def _parsed(output: ReplayArmOutput) -> SarDraftContent | None:
    """Parse one real output without grounding, or None when it is not valid SAR JSON."""
    try:
        return parse_only(output.content)
    except SarSchemaError:
        return None


def _accepted(case: ReplayCase, output: ReplayArmOutput) -> SarDraftContent | None:
    """Return the content the deterministic gate accepts for this real output, else None."""
    content = _parsed(output)
    if content is None:
        return None
    verdict = replay_gate().evaluate(
        content,
        available=case.offered_citations(),
        catalog=_EMPTY_CATALOG,
        finish_reason=output.finish_reason,
        available_evidence_refs=case.available_evidence_refs,
    )
    return content if verdict.passed else None


async def _mock_result(sar_input: SarInput):
    drafter = MockSarDrafter(SarPromptTemplate.load(), gate=production_gate())
    events = [event async for event in drafter.draft(sar_input)]
    return events[-1].result


@pytest.mark.parametrize("arm", [AWQ_ARM, BF16_ARM])
def test_every_gate_accepted_real_draft_cites_only_offered_ids(arm: str) -> None:
    """Precision is 1.0 on real output once the gate decides — the claim the release is about."""
    corpus = load_replay_corpus()
    quality = load_quality_config().sar_quality
    precision_scores: list[float] = []
    recall_scores: list[float] = []

    for case, output in corpus.arm(arm):
        content = _accepted(case, output)
        if content is None:
            continue
        metric = citation_precision_recall(
            content.cited_regulations, case.offered_citation_ids, case.expected_citation_ids
        )
        precision_scores.append(metric.precision)
        recall_scores.append(metric.recall)

    assert precision_scores, f"the {arm} arm accepted no draft at all"
    assert min(precision_scores) >= quality.citation_precision_min
    # Recall is a sampling statistic, so it binds where it was actually measured: the committed
    # floor is checked against the full 1,000-case run, and the 40-case corpus is locked to the
    # value recorded when it was drawn so a silent resample cannot drift it.
    assert corpus.population.recall_mean(arm) >= quality.citation_recall_min
    assert statistics.mean(recall_scores) == pytest.approx(corpus.sample.recall_mean(arm))


def test_the_corpus_breaches_precision_when_the_gate_is_bypassed() -> None:
    """The corpus is non-vacuous: ungated, real output misses the committed precision floor."""
    quality = load_quality_config().sar_quality
    ungated: list[float] = []

    for case, output in load_replay_corpus().arm(AWQ_ARM):
        content = _parsed(output)
        if content is None:
            continue
        ungated.append(
            citation_precision_recall(
                content.cited_regulations, case.offered_citation_ids, case.expected_citation_ids
            ).precision
        )

    assert min(ungated) < quality.citation_precision_min


def test_every_recorded_replay_verdict_is_reproduced_exactly() -> None:
    """The gate's verdict on every committed real output still matches what was recorded."""
    corpus = load_replay_corpus()

    for arm in (AWQ_ARM, BF16_ARM):
        for case, output in corpus.arm(arm):
            content = _parsed(output)
            if content is None:
                assert not output.expected_passed
                assert output.expected_reasons == ("schema_invalid",)
                continue
            verdict = replay_gate().evaluate(
                content,
                available=case.offered_citations(),
                catalog=_EMPTY_CATALOG,
                finish_reason=output.finish_reason,
                available_evidence_refs=case.available_evidence_refs,
            )
            assert verdict.passed is output.expected_passed, f"{arm}/{case.case_id}"
            assert tuple(reason.value for reason in verdict.reasons) == output.expected_reasons


@pytest.mark.asyncio
async def test_all_sar_eval_scenarios_meet_required_fact_coverage() -> None:
    """The current prompt-v2 drafting path restates every required case fact it is given."""
    config = load_sar_eval_config()
    scenarios = generate_scenarios(config, DEFAULT_SAR_EVAL_CONFIG.read_bytes()).scenarios
    citations = _citation_map()
    quality = load_quality_config().sar_quality
    coverage_scores: list[float] = []

    for scenario in scenarios:
        subject = scenario.transactions[-1]
        offered = tuple(citations[item] for item in scenario.expected_citation_ids)
        sar_input = SarInput(
            agency_id="synthetic-quality-tenant",
            transaction_id=scenario.subject_external_id,
            source="synthetic-generator",
            risk_band=RiskBand.HIGH,
            fraud_probability=0.91,
            amount=subject.amount,
            currency=subject.currency,
            country=subject.country,
            channel=subject.channel,
            direction=TransactionDirection.OUTBOUND,
            occurred_at=subject.occurred_at.astimezone(UTC),
            model_version=config.calibration.model_version,
            rules_version="quality-rules-v1",
            rag_version="quality-rag-v1",
            citations=offered,
        )
        result = await _mock_result(sar_input)
        # Required facts come from the PROJECTION, not the raw case: a `citation_bait` scenario
        # smuggles "reference 31 CFR 9999.999" into the channel, and model egress normalises that
        # to `unknown` before drafting. Requiring the raw string would demand the draft echo text
        # the allowlist deliberately suppressed.
        projected = project_for_model(sar_input, load_egress_policy()).transaction
        required = (
            str(projected.amount),
            projected.currency,
            projected.channel,
            projected.country,
            "91.0%",
            RiskBand.HIGH.value,
        )
        assert result.quality is not None and result.quality.passed
        coverage_scores.append(required_fact_coverage(required, result.content).coverage)

    assert len(coverage_scores) == _EXPECTED_SCENARIOS
    assert min(coverage_scores) >= quality.required_fact_coverage_min


def test_stricter_temporary_threshold_rejects_a_partial_fixture(sandbox: Path) -> None:
    config_text = (_REPO_ROOT / "config" / "quality.yaml").read_text(encoding="utf-8")
    strict_path = sandbox / "quality.yaml"
    strict_path.write_text(
        config_text.replace("citation_recall_min: 0.9", "citation_recall_min: 0.95"),
        encoding="utf-8",
    )
    threshold = load_quality_config(strict_path).sar_quality.citation_recall_min
    partial = citation_precision_recall(("reg-a",), ("reg-a", "reg-b"), ("reg-a", "reg-b"))

    with pytest.raises(AssertionError):
        assert partial.recall >= threshold


def test_the_corpus_population_figures_are_derived_by_code_not_typed_into_the_fixture() -> None:
    """The recall floor must bind on a number committed code re-derives from the persisted run."""
    corpus = load_replay_corpus()
    pilot = CascadeReplayPilot.model_validate_json(REPLAY_PILOT_PATH.read_bytes())
    level = next(item for item in pilot.levels if item.concurrency == corpus.concurrency)

    assert pilot.run_id == corpus.run_id
    assert pilot.policy_version == corpus.policy_version
    for arm in (AWQ_ARM, BF16_ARM):
        # Four decimals is the resolution the corpus records its provenance at.
        assert level.arm_recall_mean[arm] == pytest.approx(
            corpus.population.recall_mean(arm), abs=5e-5
        )
        assert level.arm_pass_rate[arm] == pytest.approx(corpus.population.pass_rate(arm), abs=5e-4)
