apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fraudlens
resources:
  - job.yaml
configMapGenerator:
  - name: fraudlens-load-config
    envs:
      - load.env
images:
  - name: fraudlens-backend
    newName: fraudlens-backend
    newTag: local
