"""Summary: Deterministic renderers for the generated documentation — the OpenAPI
endpoint inventory, the AppSettings config-key table, the package module-map, and
the (placeholder) ERD — plus a helper to splice generated text into the AUTOGEN
regions of a Markdown document. All output is stable for a given codebase (sorted,
no timestamps) so `make docs-check` can diff it byte-for-byte.

Key classes:
- (none)

Key functions:
- render_endpoints: Markdown table of the app's HTTP routes.
- render_config_keys: Markdown table of AppSettings fields.
- render_module_map: Mermaid graph of the package layering.
- render_erd: Mermaid ER diagram (placeholder until SQLAlchemy models land).
- replace_region: replace the body of a single <!-- AUTOGEN:name --> region.

Notes:
- render_erd tolerates "no models yet"; it is rewritten once tenant tables exist
  (each must carry agency_id).
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from fastapi.routing import APIRoute

if TYPE_CHECKING:
    from fastapi import FastAPI
    from pydantic_settings import BaseSettings

_DOCS_PATHS = ("/openapi.json", "/docs", "/redoc", "/docs/oauth2-redirect")


def render_endpoints(app: FastAPI) -> str:
    """Return a Markdown table of the application's HTTP routes, sorted by path."""
    rows: list[tuple[str, str, str]] = []
    for route in app.routes:
        if not isinstance(route, APIRoute) or route.path in _DOCS_PATHS:
            continue
        methods = sorted(route.methods - {"HEAD", "OPTIONS"})
        for method in methods:
            rows.append((route.path, method, route.name))
    rows.sort()
    lines = ["| Method | Path | Handler |", "| --- | --- | --- |"]
    lines += [f"| {method} | `{path}` | `{name}` |" for path, method, name in rows]
    return "\n".join(lines)


def render_config_keys(settings_cls: type[BaseSettings]) -> str:
    """Return a Markdown table of the settings model's fields (key/type/default/desc)."""
    lines = ["| Key | Type | Default | Description |", "| --- | --- | --- | --- |"]
    for name, field in settings_cls.model_fields.items():
        annotation = field.annotation
        type_name = getattr(annotation, "__name__", str(annotation)).replace("typing.", "")
        default = "_required_" if field.is_required() else f"`{field.default!r}`"
        description = field.description or ""
        lines.append(f"| `{name}` | `{type_name}` | {default} | {description} |")
    return "\n".join(lines)


def render_module_map() -> str:
    """Return a Mermaid graph of the internal package layering (rule: no cycles)."""
    return "\n".join(
        [
            "```mermaid",
            "graph TD",
            '    core["fraudlens-core<br/>(domain types, tenancy)"]',
            '    llm["fraudlens-llm<br/>(catalog client, guardrails)"]',
            '    ml["fraudlens-ml<br/>(scoring/RAG; placeholder)"]',
            '    backend["fraudlens-backend<br/>(FastAPI service)"]',
            "    ml --> core",
            "    backend --> core",
            "    backend -.may use.-> llm",
            "    backend -.may use.-> ml",
            "    ml -.may use.-> llm",
            "```",
        ]
    )


def render_erd() -> str:
    """Return the Mermaid ER diagram; a placeholder until SQLAlchemy models exist."""
    return "\n".join(
        [
            "```mermaid",
            "erDiagram",
            "    %% No SQLAlchemy models defined yet (foundation walking skeleton).",
            "    %% Regenerated by `make docs`; every tenant-scoped table will carry",
            "    %% agency_id (Aegis multi-tenant isolation).",
            "```",
        ]
    )


def replace_region(text: str, name: str, body: str) -> str:
    """Replace the content between <!-- AUTOGEN:name --> and <!-- /AUTOGEN:name -->."""
    pattern = re.compile(
        rf"(<!-- AUTOGEN:{re.escape(name)} -->\n).*?(\n<!-- /AUTOGEN:{re.escape(name)} -->)",
        re.DOTALL,
    )
    if not pattern.search(text):
        raise ValueError(f"AUTOGEN region '{name}' not found")
    return pattern.sub(lambda m: f"{m.group(1)}{body}{m.group(2)}", text)
