"""Summary: The `make docs` / `make docs-check` engine. In write mode it (1) syncs
the machine-owned Key classes/functions inventory lines in every SUMMARY header,
(2) regenerates the OpenAPI schema + endpoint list from the live FastAPI app, (3)
regenerates the ERD from live SQLAlchemy metadata, and (4) refreshes
the AUTOGEN regions of the architecture doc. With --check it regenerates everything
in memory, diffs against what is committed, and fails if anything is stale — so CI
blocks drift between code and docs. All output is deterministic (sorted, no clocks).

Key classes:
- (none)

Key functions:
- main: CLI entry; run or --check the requested doc target(s).

Notes:
- Targets: all (default), headers, openapi, erd, arch. `make openapi` uses
  `--check openapi` as a focused sync gate.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import TYPE_CHECKING

from fraudlens_backend.main import create_app
from fraudlens_backend.settings import AppSettings
from lib.docs_arch import (
    render_config_keys,
    render_endpoints,
    render_erd,
    render_module_map,
    replace_region,
)
from lib.headers import iter_source_files, sync_header, validate_header

if TYPE_CHECKING:
    from fastapi import FastAPI

REPO_ROOT = Path(__file__).resolve().parents[1]
API_DIR = REPO_ROOT / "docs" / "reference" / "generated" / "api"
ERD_DIR = REPO_ROOT / "docs" / "reference" / "generated" / "erd"
ARCH_DOC = REPO_ROOT / "docs" / "architecture" / "ARCHITECTURE.md"


def _load_app() -> FastAPI:
    """Construct the FastAPI app with default settings for schema generation."""
    return create_app(AppSettings())


def _openapi_json(app: FastAPI) -> str:
    """Return the app's OpenAPI schema as deterministic, sorted JSON."""
    return json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"


def _endpoints_md(app: FastAPI) -> str:
    """Return the human-readable endpoint inventory Markdown."""
    header = "# API endpoints\n\n> Generated by `make docs` — do not edit by hand.\n\n"
    return header + render_endpoints(app) + "\n"


def _arch_text(app: FastAPI, current: str) -> str:
    """Return ARCHITECTURE.md with its AUTOGEN regions refreshed from code."""
    text = replace_region(current, "endpoints", render_endpoints(app))
    text = replace_region(text, "config-keys", render_config_keys(AppSettings))
    text = replace_region(text, "module-map", render_module_map())
    return replace_region(text, "erd", render_erd())


def _emit(path: Path, content: str, *, check: bool, stale: list[Path], changed: list[Path]) -> None:
    """Write content (or, in check mode, record staleness) when it differs from disk."""
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return
    if check:
        stale.append(path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    changed.append(path)


def main() -> int:
    """Generate (or --check) the requested documentation target(s)."""
    parser = argparse.ArgumentParser(description="Regenerate or validate generated docs.")
    parser.add_argument(
        "target",
        nargs="?",
        default="all",
        choices=["all", "headers", "openapi", "erd", "arch"],
    )
    parser.add_argument("--check", action="store_true", help="diff only; fail if stale")
    args = parser.parse_args()
    target: str = args.target
    check: bool = args.check

    stale: list[Path] = []
    changed: list[Path] = []

    if target in {"all", "headers"}:
        for path in iter_source_files(REPO_ROOT):
            if check:
                if validate_header(path):
                    stale.append(path)
            elif sync_header(path):
                changed.append(path)

    if target in {"all", "openapi"}:
        app = _load_app()
        _emit(
            API_DIR / "openapi.json", _openapi_json(app), check=check, stale=stale, changed=changed
        )
        _emit(
            API_DIR / "endpoints.md", _endpoints_md(app), check=check, stale=stale, changed=changed
        )

    if target in {"all", "erd"}:
        _emit(ERD_DIR / "erd.mmd", render_erd() + "\n", check=check, stale=stale, changed=changed)

    if target in {"all", "arch"} and ARCH_DOC.exists():
        app = _load_app()
        rewritten_arch = _arch_text(app, ARCH_DOC.read_text(encoding="utf-8"))
        _emit(ARCH_DOC, rewritten_arch, check=check, stale=stale, changed=changed)

    if check:
        if stale:
            print("docs-check FAILED — stale (run `make docs`):")
            for path in stale:
                print(f"  {path.relative_to(REPO_ROOT)}")
            return 1
        print("docs-check OK: headers + generated docs are in sync")
        return 0
    for path in changed:
        print(f"updated {path.relative_to(REPO_ROOT)}")
    if not changed:
        print("docs: already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
